# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('id_usuario', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
