# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNotaSalida',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_salida', models.IntegerField()),
                ('id_lote', models.IntegerField()),
                ('nombre_materia_prima', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'detalle_nota_salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaSalida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('id_personal', models.IntegerField()),
            ],
            options={
                'db_table': 'nota_salida',
                'managed': False,
            },
        ),
    ]
