# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=45)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
    ]
