# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_marcado', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('id_personal', models.IntegerField()),
                ('id_turno', models.IntegerField()),
            ],
            options={
                'db_table': 'control_asistencia',
                'managed': False,
            },
        ),
    ]
