# Generated by Django 5.2.6 on 2025-09-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usurios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100, unique=True)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
