# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField()),
                ('resultado', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('id_personal', models.IntegerField()),
                ('id_trazabilidad', models.IntegerField()),
            ],
            options={
                'db_table': 'control_calidad',
                'managed': False,
            },
        ),
    ]
