# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia_prima', models.CharField(max_length=255)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_lote', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
    ]
