# Generated by Django 5.2.6 on 2025-09-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turnos',
            fields=[
                ('id_turnos', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=20)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
    ]
