# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(max_length=100, unique=True)),
                ('fecha_recepcion', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('id_materia', models.IntegerField()),
            ],
            options={
                'db_table': 'lotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'materias_primas',
                'managed': False,
            },
        ),
    ]
