# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id_trazabilidad', models.AutoField(primary_key=True, serialize=False)),
                ('proceso', models.CharField(max_length=255)),
                ('descripcion_proceso', models.TextField()),
                ('fecha_registro', models.DateTimeField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('id_personal', models.IntegerField()),
                ('id_orden', models.IntegerField()),
            ],
            options={
                'db_table': 'trazabilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadLote',
            fields=[
                ('id_trazabilidad_lote', models.AutoField(primary_key=True, serialize=False)),
                ('id_lote', models.IntegerField()),
                ('id_materia', models.IntegerField()),
                ('nombre_materia', models.CharField(max_length=255)),
                ('codigo_lote', models.CharField(max_length=100)),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('id_operacion', models.IntegerField()),
                ('codigo_operacion', models.CharField(max_length=100)),
                ('fecha_consumo', models.DateTimeField()),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'trazabilidad_lote',
                'managed': False,
            },
        ),
    ]
