# Generated by Django 5.2.6 on 2025-11-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cod_orden', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('producto_modelo', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=50)),
                ('cantidad_total', models.IntegerField()),
                ('id_personal', models.IntegerField()),
            ],
            options={
                'db_table': 'orden_produccion',
                'managed': False,
            },
        ),
    ]
